version: '3'
services:
  flask:
    build: ./flask
    image: flask
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=flask"
      - "traefik.frontend.rule=Host:plant.lauszus.com"
    volumes:
      - ./flask/app/update:/flask/app/update:rw
  traefik:
    image: traefik:v1.7
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik/acme:/etc/traefik/acme
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
